from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol
from uuid import UUID

from athena.events import AudioChunk


class SpeechSynthesizer(Protocol):
    async def connect(self) -> None: ...
    async def send_text(self, turn_id: UUID, text: str) -> None: ...
    def audio(self) -> AsyncIterator[AudioChunk]: ...
    async def flush(self, turn_id: UUID) -> None: ...
    async def cancel(self, turn_id: UUID) -> None: ...
    async def close(self) -> None: ...
