let csrf="", historyTimer=null, statusTimer=null, musicTimer=null, volumeTimer=null, audioContext=null;
const $=id=>document.getElementById(id);
async function api(path,options={}){options.headers={"Content-Type":"application/json",...(options.headers||{})};if(options.method&&options.method!=="GET")options.headers["X-ATHENA-CSRF"]=csrf;const r=await fetch(path,options);if(!r.ok)throw new Error(await r.text()||`Request failed (${r.status})`);return r.json()}
function serviceView(data){const active=data.service==="active";$('statusDot').className=`dot ${active?'active':data.service==='failed'?'failed':''}`;$('serviceLabel').textContent=data.serviceLabel;$('serviceHeading').textContent=active?'Voice is online':'Voice is offline'}
async function boot(){try{const data=await api('/api/bootstrap');csrf=data.csrf;serviceView(data);$('systemPrompt').value=data.prompts.system;$('memoryPrompt').value=data.prompts.memory;$('login').hidden=true;$('app').hidden=false;startRefresh()}catch(e){$('login').hidden=false;$('app').hidden=true}}
function startRefresh(){clearInterval(statusTimer);statusTimer=setInterval(async()=>{try{serviceView(await api('/api/status'))}catch{}},3000);loadHistory();clearInterval(historyTimer);historyTimer=setInterval(()=>{if($('history').classList.contains('active'))loadHistory()},5000);loadMusic();clearInterval(musicTimer);musicTimer=setInterval(loadMusic,1000)}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({password:$('password').value})});csrf=d.csrf;$('password').value='';await boot()}catch(err){$('loginError').textContent=err.message}});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active');if(b.dataset.page==='history')loadHistory()}));
document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',async()=>{document.querySelectorAll('[data-service]').forEach(x=>x.disabled=true);$('controlMessage').textContent=`Sending ${b.dataset.service} command…`;try{const d=await api('/api/service',{method:'POST',body:JSON.stringify({action:b.dataset.service})});serviceView(d);$('controlMessage').textContent=d.serviceLabel}catch(e){$('controlMessage').textContent=e.message}finally{document.querySelectorAll('[data-service]').forEach(x=>x.disabled=false)}}));
function musicView(d){const playing=!!d.playing,paused=!!d.paused;$('musicState').textContent=paused?'PAUSED':playing?'PLAYING':'IDLE';$('musicState').className=`music-state ${paused?'paused':playing?'playing':''}`;$('musicTitle').textContent=d.title||'No track loaded';$('musicToggle').textContent=paused?'Play':'Pause';$('musicToggle').disabled=!playing;if(document.activeElement!==$('musicVolume')){$('musicVolume').value=d.volume;$('musicVolumeLabel').textContent=`${d.volume}%`}if(d.error)$('musicMessage').textContent=d.error}
async function loadMusic(){try{musicView(await api('/api/music'))}catch(e){$('musicState').textContent='OFFLINE';$('musicState').className='music-state';$('musicMessage').textContent=e.message}}
async function musicAction(action,value){document.querySelectorAll('.music-buttons button').forEach(x=>x.disabled=true);try{const d=await api('/api/music',{method:'POST',body:JSON.stringify({action,...(value===undefined?{}:{value})})});musicView(d);$('musicMessage').textContent=action==='volume'?`Music volume set to ${d.volume}%.`:'Music control applied.'}catch(e){$('musicMessage').textContent=e.message}finally{document.querySelectorAll('.music-buttons button').forEach(x=>x.disabled=false);loadMusic()}}
$('musicToggle').addEventListener('click',()=>musicAction('toggle'));
$('musicNext').addEventListener('click',()=>musicAction('next'));
$('musicStop').addEventListener('click',()=>musicAction('stop'));
$('musicVolume').addEventListener('input',e=>{const value=Number(e.target.value);$('musicVolumeLabel').textContent=`${value}%`;clearTimeout(volumeTimer);volumeTimer=setTimeout(()=>musicAction('volume',value),120)});
function message(text,who,extra=''){const node=document.createElement('div');node.className=`message ${who} ${extra}`;node.textContent=text;$('messages').append(node);$('messages').scrollTop=$('messages').scrollHeight;return node}
function armDeviceAudio(){if($('replyOutput').value!=='device')return;if(!audioContext)audioContext=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume()}
async function speakReply(text){const target=$('replyOutput').value;if(target==='off')return;try{if(target==='athena'){await api('/api/speech/athena',{method:'POST',body:JSON.stringify({text})});return}const r=await fetch('/api/speech/device',{method:'POST',headers:{'Content-Type':'application/json','X-ATHENA-CSRF':csrf},body:JSON.stringify({text})});if(!r.ok)throw new Error(await r.text());const data=await r.arrayBuffer();const decoded=await audioContext.decodeAudioData(data);const source=audioContext.createBufferSource();source.buffer=decoded;source.connect(audioContext.destination);source.start()}catch(e){message(`Audio: ${e.message}`,'athena')}}
async function poll(id,node){for(;;){await new Promise(r=>setTimeout(r,500));try{const d=await api(`/api/chat/${id}`);if(d.status==='complete'){node.classList.remove('pending');node.textContent=d.answer;$('taskCount').textContent='READY';loadHistory();speakReply(d.answer);return}}catch(e){node.classList.remove('pending');node.textContent=e.message;$('taskCount').textContent='ERROR';return}}}
$('chatForm').addEventListener('submit',async e=>{e.preventDefault();const text=$('chatInput').value.trim();if(!text)return;armDeviceAudio();$('chatInput').value='';message(text,'user');const waiting=message('Working in the background…','athena','pending');$('taskCount').textContent='WORKING';try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({text})});poll(d.id,waiting)}catch(err){waiting.classList.remove('pending');waiting.textContent=err.message;$('taskCount').textContent='ERROR'}});
$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('chatForm').requestSubmit()}});
async function loadHistory(){try{const d=await api('/api/conversations');const list=$('conversationList');list.replaceChildren();if(!d.conversations.length){const p=document.createElement('p');p.className='muted';p.textContent='No saved conversations yet.';list.append(p);return}for(const row of d.conversations){const box=document.createElement('article');box.className='conversation';const t=document.createElement('time');t.textContent=new Date(row.at).toLocaleString();const q=document.createElement('p');q.className='q';q.textContent=`You: ${row.user}`;const a=document.createElement('p');a.className='a';a.textContent=`ATHENA: ${row.assistant}`;box.append(t,q,a);list.append(box)}}catch(e){$('conversationList').textContent=e.message}}
$('refreshHistory').addEventListener('click',loadHistory);
$('savePrompts').addEventListener('click',async()=>{const b=$('savePrompts');b.disabled=true;$('saveMessage').textContent='Saving…';try{const d=await api('/api/prompts',{method:'POST',body:JSON.stringify({system:$('systemPrompt').value,memory:$('memoryPrompt').value})});$('saveMessage').textContent=d.message}catch(e){$('saveMessage').textContent=e.message}finally{b.disabled=false}});
$('logout').addEventListener('click',async()=>{try{await api('/api/logout',{method:'POST',body:'{}'})}catch{}location.reload()});
boot();
