from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol
from uuid import UUID

from athena.events import Transcript


class SpeechRecognizer(Protocol):
    async def connect(self) -> None: ...
    async def start_turn(self, turn_id: UUID) -> None: ...
    async def send_audio(self, pcm: bytes) -> None: ...
    def results(self) -> AsyncIterator[Transcript]: ...
    async def finish_turn(self) -> None: ...
    async def close(self) -> None: ...
